const crypto = require('crypto');

/**
 * StyleProcessor is responsible for handling all CSS-related logic during the build process.
 * This includes managing global CSS variables, scoping component-specific styles using hashes,
 * and extracting CSS rules into a global stylesheet.
 */
class StyleProcessor {
    /**
     * Tracks which hashes have already been added to globalStyles to prevent duplicates.
     * @type {Set<string>}
     * @private
     */
    #addedHashes = new Set();

    /**
     * Creates an instance of StyleProcessor.
     */
    constructor() {
        this.reset();
    }

    /**
     * Resets the processor state, clearing all accumulated styles and variables.
     */
    reset() {
        /** 
         * The accumulated global stylesheet content.
         * @type {string} 
         */
        this.globalStyles = "";
        
        /** 
         * A map of CSS variable names to their values.
         * @type {Object<string, string>} 
         */
        this.cssVariables = {};
        
        /**
         * Raw global CSS rules added via addGlobalCSS.
         * @type {Set<string>}
         */
        this.rawGlobalCSS = new Set();
        
        /**
         * Scoped CSS rules.
         * @type {string}
         */
        this.scopedStyles = "";

        this.#addedHashes = new Set();
    }

    /**
     * Adds a global CSS variable to the processor.
     * @param {string} name - The name of the variable (without the @ prefix).
     * @param {string} value - The value of the variable.
     */
    addVariable(name, value) {
        this.cssVariables[name] = value;
    }

    /**
     * Adds raw global CSS rules to the stylesheet.
     * @param {string} css - The raw CSS string.
     */
    addGlobalCSS(css) {
        this.rawGlobalCSS.add(css);
    }

    /**
     * Retrieves the accumulated global styles.
     * @returns {string} The complete CSS string for the application.
     */
    getGlobalStyles() {
        let output = "/* Generated by Avenx-JS */\n";
        
        // 1. Global CSS rules
        for (const css of this.rawGlobalCSS) {
            output += this.applyVariables(css) + "\n";
        }
        
        // 2. Scoped styles
        output += "\n/* Scoped Styles */\n" + this.scopedStyles;
        
        return output;
    }

    /**
     * Processes the CSS within an HTML template. It identifies <@css> tags
     * and @css attributes, scopes the rules with a unique hash, replaces variables,
     * and updates the HTML to include the hash class.
     * @param {string} html - The HTML template.
     * @param {Object} [desBlocks={}] - Pre-defined style blocks from an .axd file.
     * @param {string} [componentName=""] - The name of the component for hash generation.
     * @returns {string} The modified HTML.
     */
    process(html, desBlocks = {}, componentName = "") {
        let modifiedHtml = html;

        // 1. First, handle all @css attributes (new syntax)
        // This replaces '@css name' with 'class="hash"' or merges with existing classes
        modifiedHtml = modifiedHtml.replace(/<([^>]+)\s+@css\s+([\w-]+)([^>]*)>/g, (fullMatch, before, blockName, after) => {
            const cssContent = desBlocks[blockName] || "";
            if (!cssContent) return `<${before}${after}>`;

            const hash = this.getHash(cssContent, componentName);
            this.extractRules(this.applyVariables(cssContent), hash);

            const tagWithClass = this.mergeClassIntoTag(before + after, hash);
            return `<${tagWithClass}>`;
        });

        // 2. Then, handle all <@css /> tags (old/anonymous syntax)
        const tagRegex = /<@css\s+([\w-]+)?\s*\/?>/g;
        let match;
        
        while ((match = tagRegex.exec(modifiedHtml)) !== null) {
            const fullMatch = match[0];
            const blockName = match[1];
            const cssContent = blockName ? (desBlocks[blockName] || "") : "";

            if (!cssContent) {
                modifiedHtml = modifiedHtml.replace(fullMatch, '');
                tagRegex.lastIndex = 0; // Restart because string changed
                continue;
            }

            const hash = this.getHash(cssContent, componentName);
            this.extractRules(this.applyVariables(cssContent), hash);

            const matchIndex = match.index;
            const beforeMatch = modifiedHtml.substring(0, matchIndex);
            const lastTagStart = beforeMatch.lastIndexOf('<');
            const lastTagEnd = beforeMatch.lastIndexOf('>');

            if (lastTagStart !== -1 && lastTagStart > lastTagEnd) {
                // Inside a tag: <div <@css ... /> >
                const tagContent = modifiedHtml.substring(lastTagStart + 1, matchIndex);
                const updatedTag = this.mergeClassIntoTag(tagContent, hash);
                modifiedHtml = modifiedHtml.substring(0, lastTagStart + 1) + 
                               updatedTag + 
                               modifiedHtml.substring(matchIndex + fullMatch.length);
            } else {
                // Outside a tag: <div> <@css ... /> </div>
                // Search for the previous tag to apply the class to
                const prevTagRegex = /<([a-zA-Z0-9-]+)([^>]*)>$/;
                const prevTagMatch = beforeMatch.trimEnd().match(prevTagRegex);
                
                if (prevTagMatch) {
                    const tagStart = beforeMatch.lastIndexOf(prevTagMatch[0]);
                    const tagContent = prevTagMatch[1] + prevTagMatch[2];
                    const updatedTag = this.mergeClassIntoTag(tagContent, hash);
                    
                    modifiedHtml = modifiedHtml.substring(0, tagStart + 1) +
                                   updatedTag +
                                   '>' +
                                   modifiedHtml.substring(tagStart + prevTagMatch[0].length, matchIndex) +
                                   modifiedHtml.substring(matchIndex + fullMatch.length);
                } else {
                    modifiedHtml = modifiedHtml.replace(fullMatch, '');
                }
            }
            tagRegex.lastIndex = 0; // Restart because string changed
        }

        return modifiedHtml;
    }

    /**
     * Merges a CSS class hash into an existing tag string, handling existing class attributes.
     * @private
     */
    mergeClassIntoTag(tagContent, hash) {
        const classRegex = /class=["']([^"']*)["']/;
        const match = tagContent.match(classRegex);

        if (match) {
            const existingClasses = match[1];
            if (existingClasses.includes(hash)) return tagContent;
            return tagContent.replace(classRegex, `class="${hash} ${existingClasses}"`);
        } else {
            // Check if it's a self-closing tag or has other attributes
            if (tagContent.trim().endsWith('/')) {
                return tagContent.replace(/\s*\/$/, ` class="${hash}" /`);
            }
            return tagContent.trimEnd() + ` class="${hash}"`;
        }
    }

    applyVariables(cssContent) {
        let content = cssContent;
        // Sort variables by length descending to prevent partial replacement (e.g., @primary vs @primary-hover)
        const sortedVars = Object.entries(this.cssVariables).sort((a, b) => b[0].length - a[0].length);
        
        for (const [varName, varValue] of sortedVars) {
            // Use a negative lookahead to ensure we don't match a partial variable name
            // that is actually followed by a hyphen or word characters.
            const varRegex = new RegExp(`@${varName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![\\w-])`, 'g');
            content = content.replace(varRegex, varValue);
        }
        return content;
    }

    getHash(cssContent, componentName) {
        return "avenx-" + crypto.createHash('md5').update(cssContent + componentName).digest('hex').substring(0, 8);
    }

    /**
     * Extracts CSS rules from a content string, scopes them using the provided hash,
     * and appends them to the global stylesheet.
     * @private
     */
    extractRules(cssContent, hash) {
        if (this.#addedHashes.has(hash)) return;
        this.#addedHashes.add(hash);

        let baseRules = "";
        let nestedRules = "";
        let current = "";
        let depth = 0;

        const processPart = (part) => {
            let rule = part.trim();
            if (!rule) return;

            if (rule.includes('{')) {
                // It's a nested rule or a media query
                const selectorMatch = rule.match(/^([^{]+)\{([\s\S]*)\}$/);
                if (selectorMatch) {
                    let selector = selectorMatch[1].trim();
                    const body = selectorMatch[2].trim();
                    
                    if (selector.includes('&')) {
                        selector = selector.replace(/&/g, `.${hash}`);
                    } else {
                        selector = `.${hash}${selector}`;
                    }
                    nestedRules += `${selector} { ${body} }\n`;
                }
            } else {
                // It's one or more base properties (e.g. "color: red; margin: 0;")
                const props = rule.split(';').map(p => p.trim()).filter(p => p.length > 0);
                props.forEach(prop => {
                    baseRules += prop + "; ";
                });
            }
        };

        for (let char of cssContent) {
            current += char;
            if (char === '{') depth++;
            else if (char === '}') depth--;
            
            if (depth === 0 && (char === ';' || char === '}')) {
                processPart(current);
                current = "";
            }
        }

        if (current.trim()) processPart(current);

        if (baseRules.trim()) this.scopedStyles += `.${hash} { ${baseRules.trim()} }\n`;
        if (nestedRules.trim()) this.scopedStyles += nestedRules + "\n";
    }
}

module.exports = StyleProcessor;
