const crypto = require('crypto');

/**
 * StyleProcessor is responsible for handling all CSS-related logic during the build process.
 * This includes managing global CSS variables, scoping component-specific styles using hashes,
 * and extracting CSS rules into a global stylesheet.
 */
class StyleProcessor {
    /**
     * Tracks which hashes have already been added to globalStyles to prevent duplicates.
     * @type {Set<string>}
     * @private
     */
    #addedHashes = new Set();

    /**
     * Creates an instance of StyleProcessor.
     */
    constructor() {
        /** 
         * The accumulated global stylesheet content.
         * @type {string} 
         */
        this.globalStyles = "/* Generated by Avenx-JS (Scoped CSS) */\n";
        
        /** 
         * A map of CSS variable names to their values.
         * @type {Object<string, string>} 
         */
        this.cssVariables = {};
        
        this.#addedHashes = new Set();
    }

    /**
     * Adds a global CSS variable to the processor.
     * @param {string} name - The name of the variable (without the @ prefix).
     * @param {string} value - The value of the variable.
     */
    addVariable(name, value) {
        this.cssVariables[name] = value;
    }

    /**
     * Retrieves the accumulated global styles.
     * @returns {string} The complete CSS string for the application.
     */
    getGlobalStyles() {
        return this.globalStyles;
    }

    /**
     * Processes the CSS within an HTML template. It identifies <@css> tags
     * and @css attributes, scopes the rules with a unique hash, replaces variables,
     * and updates the HTML to include the hash class.
     * @param {string} html - The HTML template.
     * @param {Object} [desBlocks={}] - Pre-defined style blocks from an .axd file.
     * @param {string} [componentName=""] - The name of the component for hash generation.
     * @returns {string} The modified HTML.
     */
    process(html, desBlocks = {}, componentName = "") {
        let modifiedHtml = html;

        // 1. First, handle all @css attributes (new syntax)
        // This replaces '@css name' with 'class="hash"' or merges with existing classes
        modifiedHtml = modifiedHtml.replace(/<([^>]+)\s+@css\s+(\w+)([^>]*)>/g, (fullMatch, before, blockName, after) => {
            const cssContent = desBlocks[blockName] || "";
            if (!cssContent) return `<${before}${after}>`;

            const hash = this.getHash(cssContent, componentName);
            this.extractRules(this.applyVariables(cssContent), hash);

            const tagWithClass = this.mergeClassIntoTag(before + after, hash);
            return `<${tagWithClass}>`;
        });

        // 2. Then, handle all <@css /> tags (old/anonymous syntax)
        const tagRegex = /<@css\s*(\w+)?\s*>([\s\S]*?)<\/ @css>|<@css\s*(\w+)?\s*\/?>/g;
        let match;
        const tagMatches = [];
        while ((match = tagRegex.exec(modifiedHtml)) !== null) {
            tagMatches.push(match);
        }

        let anonymousIndex = 0;
        for (let i = tagMatches.length - 1; i >= 0; i--) {
            const m = tagMatches[i];
            const blockName = m[1] || m[3];
            let cssContent = (m[2] || "").trim();
            const fullMatch = m[0];
            const matchIndex = m.index;

            if (!cssContent) {
                cssContent = blockName ? (desBlocks[blockName] || "") : (desBlocks[`__anon_${anonymousIndex++}`] || "");
            }

            if (!cssContent) {
                modifiedHtml = modifiedHtml.replace(fullMatch, '');
                continue;
            }

            const hash = this.getHash(cssContent, componentName);
            this.extractRules(this.applyVariables(cssContent), hash);

            // Apply hash to the parent tag only if <@css /> is INSIDE the tag
            // Example: <div <@css container /> >
            const beforeMatch = modifiedHtml.substring(0, matchIndex);
            const lastTagStart = beforeMatch.lastIndexOf('<');
            const lastTagEnd = beforeMatch.lastIndexOf('>');

            if (lastTagStart !== -1 && lastTagStart > lastTagEnd) {
                // We are inside a tag
                const tagContent = modifiedHtml.substring(lastTagStart + 1, matchIndex);
                const updatedTag = this.mergeClassIntoTag(tagContent, hash);
                modifiedHtml = modifiedHtml.substring(0, lastTagStart + 1) + 
                               updatedTag + 
                               modifiedHtml.substring(matchIndex + fullMatch.length);
            } else {
                // We are outside a tag (as a child), just remove the <@css /> tag
                // But we still want to apply the style to the real parent if it's a container block
                if (blockName === 'container' && lastTagStart !== -1) {
                     // Special case for container: apply to the last opened tag
                     const tagContent = modifiedHtml.substring(lastTagStart + 1, lastTagEnd);
                     const updatedTag = this.mergeClassIntoTag(tagContent, hash);
                     modifiedHtml = modifiedHtml.substring(0, lastTagStart + 1) + 
                                    updatedTag + 
                                    modifiedHtml.substring(lastTagEnd, matchIndex) +
                                    modifiedHtml.substring(matchIndex + fullMatch.length);
                } else {
                    modifiedHtml = modifiedHtml.replace(fullMatch, '');
                }
            }
        }

        return modifiedHtml;
    }

    /**
     * Merges a CSS class hash into an existing tag string, handling existing class attributes.
     * @private
     */
    mergeClassIntoTag(tagContent, hash) {
        const classRegex = /class=["']([^"']*)["']/;
        const match = tagContent.match(classRegex);

        if (match) {
            const existingClasses = match[1];
            if (existingClasses.includes(hash)) return tagContent;
            return tagContent.replace(classRegex, `class="${hash} ${existingClasses}"`);
        } else {
            // Append class attribute before the end of the tag opening
            if (tagContent.trim().endsWith('/')) {
                return tagContent.replace(/\s*\/$/, ` class="${hash}" /`);
            }
            return tagContent.trimEnd() + ` class="${hash}"`;
        }
    }

    applyVariables(cssContent) {
        let content = cssContent;
        for (const [varName, varValue] of Object.entries(this.cssVariables)) {
            const varRegex = new RegExp(`@${varName}\\b`, 'g');
            content = content.replace(varRegex, varValue);
        }
        return content;
    }

    getHash(cssContent, componentName) {
        return "avenx-" + crypto.createHash('md5').update(cssContent + componentName).digest('hex').substring(0, 8);
    }

    /**
     * Extracts CSS rules from a content string, scopes them using the provided hash,
     * and appends them to the global stylesheet.
     * @private
     */
    extractRules(cssContent, hash) {
        if (this.#addedHashes.has(hash)) return;
        this.#addedHashes.add(hash);

        let baseRules = "";
        let nestedRules = "";
        let current = "";
        let depth = 0;

        const processPart = (part) => {
            let rule = part.trim();
            if (rule.includes('{')) {
                nestedRules += rule.replace(/&/g, `.${hash}`) + "\n";
            } else if (rule && rule !== ';') {
                if (!rule.endsWith(';')) rule += ';';
                baseRules += rule + " ";
            }
        };

        for (let char of cssContent) {
            current += char;
            if (char === '{') depth++;
            else if (char === '}') depth--;
            
            if (depth === 0 && (char === ';' || char === '}')) {
                processPart(current);
                current = "";
            }
        }

        if (current.trim()) processPart(current);

        if (baseRules.trim()) this.globalStyles += `.${hash} { ${baseRules} }\n`;
        if (nestedRules.trim()) this.globalStyles += nestedRules + "\n";
    }
}

module.exports = StyleProcessor;
